Repository miewone/BeStrongCodeBeginer, pull requests merged in 2023-06, with the labels that each got.

#18 1강 리스트 원소 두개의 합 구하기
  dohyun/step_1.py
Labels: 실습

#20 16 백준 1003 피보나치 함수
  wongyun/1003/1003.py
  wongyun/1003/1003_input.txt
Labels: 백준

#25 [programmers]solution_1.py
  minji/solution_1.py
Labels: 프로그래머스

#26 [Programmers] solution_2.py
  minji/solution_2.py
Labels: 프로그래머스

#27 [Programmers] solution_3.py
  minji/solution_3.py
Labels: 프로그래머스

#35 3강 실습: 이진 탐색 구현해보기
  minji/part_3
Labels: 실습

#28 #21 1로 만들기
  wongyun/1463/1463.py
  wongyun/1463/1463_input.txt
Labels: 백준

#36 4강 실습: 피보나치 순열 구현하기
  minji/part4_recursive_function
Labels: 실습

#38 Update and rename part_3 to 이진 탐색 구현해보기
  minji/part_3
  minji/이진 탐색 구현해보기
Labels: 실습

#50 up
  wongyun/1107/1107.py
  wongyun/1107/1107_input.txt
  wongyun/11724/11724.py
  wongyun/11724/11724_input.txt
Labels: 프로그래머스

#65 Create 5강 실습: 재귀적 이진 탐색 구현하기
  minji/5강 실습: 재귀적 이진 탐색 구현하기
Labels: 실습

#66 Create 7강 실습: 연결 리스트 순회 구현하기
  minji/7강 실습: 연결 리스트 순회 구현하기
Labels: 실습

#67 Create 8강 실습: 연결 리스트 노드 삭제하기
  minji/8강 실습: 연결 리스트 노드 삭제하기
Labels: 실습

#76 Create 10강 실습: (2) 양방향 연결 리스트 노드 삽입
  minji/10강 실습: (2) 양방향 연결 리스트 노드 삽입
Labels: 실습

#69 Create 9강 실습: dummy head 를 가지는 연결 리스트 노드 삭제
  minji/9강 실습: dummy head 를 가지는 연결 리스트 노드 삭제
Labels: 실습

#77 Create (10-3) 양방향 연결 리스트 노드 삭제
  minji/(10-3) 양방향 연결 리스트 노드 삭제
Labels: 실습

#104 Create 13강 실습: 후위표현 수식 계산
  minji/13강 실습: 후위표현 수식 계산
Labels: 실습
